name = "myportfolio"  # must match Cloudflare project name exactly
pages_build_output_dir = "./build/client"

[build]
command = "npm run build"

kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]
